version: "3.9"

services:
  portfolio-app:
    container_name: "portfolio-app-${ENV}"
    image: portfolio-app
    restart: always
    env_file:
      - ./.dev.env
      - ./.qa.env
    build:
      context: ./app
      dockerfile: Dockerfile
      target: base
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./src
          target: /app
          action: sync
    ports:
      - "${PORT}:${PORT}"
