name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build ./app --file ./app/Dockerfile --tag anartisticengineer/portfolio-app:latest

      - uses: docker/login-action@v1
        name: Log in to Docker Hub
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Save state
        run: echo "{name}={value}" >> $GITHUB_STATE

      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT

      - name: Push Docker Image
        run: docker push anartisticengineer/portfolio-app:latest
